#!/bin/bash
###############################################################################################################
#
#
#
################################################################################################################
if [ $# -ne 1 ]
then
echo "Error - incorrect number of arguments passed"
echo "USAGGE - loopTillport22ComeUp IPADDRESS"
exit 1
fi
 
test=1
while [ $test -ne 0 ]
do
   nc -w 1 $1 22 </dev/null
   if [ $? -eq  0 ]
   then
             test=0
   else
             test=1
   fi
done
