---
- name: Install and configure AD authentication on BasionHost
  hosts: BasionHost
  become: yes
  remote_user: ec2-user
  tasks:
    - name: Installing softwares like firewall and openswan
      yum: name={{ item }} state=present
      with_items:
      - firewalld 
      - openswan 
      - realmd
      - krb5-workstation
      - oddjob
      - oddjob-mkhomedir 
      - sssd
      - samba-common-tools
      - libselinux-python
      - adcli
      - samba-common
      - ntpdate
      - ntp
      - python-pip
      - jq
    - name: Install pexpect using pip
      pip:
        name: pexpect
    - name: Installing  awscli using pip
      pip:
        name: awscli
    - name: Copying key file to MumNatInst for ec2-user
      copy:
        src: ../../keyDir/Vpn.public.pem
        dest: /home/ec2-user/Vpn.public.pem
        owner: ec2-user
        group: ec2-user
        mode: 0400
    - name: Changing hostname of instance to basionhost
      command:  /bin/bash -c "sudo hostnamectl set-hostname basionhost" 
    - name: Make sure firewalld is started now and at boot.
      service: name=firewalld state=started enabled=yes
    - name: Make sure ipsec is started now and at boot.
      service: name=ipsec state=started enabled=yes
    - name: Enabling masquerade permanently in firewall configuration
      command: "firewall-cmd --permanent --zone=public --add-masquerade"
    - name: Reloading firewalld
      command: "firewall-cmd --reload"
    - name: Joining Active Directory Domain
      expect:
        command: /bin/bash -c "sudo realm join -v -U administrator@amitsuneja.xyz amitsuneja.xyz"
        responses:
          Password for *: "{{ bind_password }}"
    - name: Installing Powershell on Linux
      shell:  /usr/bin/curl https://packages.microsoft.com/config/rhel/7/prod.repo | /usr/bin/sudo /usr/bin/tee /etc/yum.repos.d/microsoft.repo
    - name: Installing Powershell on Linux1
      command:  sudo yum install -y powershell
